### ISSUE TITLE
In details panel, when failing to load a .tox because of a missing license, make it clear

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4#108]
From: https://forum.derivative.ca/t/touchengine-plugin-for-unreal-engine-beta-release/190764/63?u=jetxs

It appears that when a user is trying to use TouchEngine and is missing a valid license, the details panel is only saying "Failed to load .tox file". It should be more descriptive if at all possible (if there is room). Or we should make it clear that there is details about why the .tox file failed to load printed in the console.

Thanks

**Comment by ddthejj** [comment]
Added more detail in 40117e31acb52daa648a07c152671b3c7fa46502

**Comment by jetXS** [comment]
It doesn't log any error and the squares/loading is animating forever at the moment in the case of a missing license or a non-commercial license.

![image](https://user-images.githubusercontent.com/10253645/142278855-6da2101d-43e4-4042-ab0c-0afec96af111.png)

**Comment by bangnoise** [comment]
Looks like @ddthejj has this in hand - if you don't get TEEventInstanceDidLoad with a suitable TEResult in this situation then reassign me with steps to reproduce this in code, thanks.

**Comment by ddthejj** [comment]
Hopefully fixed in 199fabaa7843f6a0e364d491682b284e0cf370ad

**Comment by jetXS** [comment]
It does appear sometimes but seems to be inconsistent.

Additionally, **any** error of the details panel / loading of .tox / missing license / TouchEngine not found should result in an Error being logged.

**Comment by ddthejj** [comment]
Should be fixed in be3049472dd5b27871f1475831fb8480952c5f60

**Comment by jetXS** [comment]
Still seeing inconsistencies, especially at startup

**Comment by ddthejj** [comment]
Okay I've fixed another error relating to objects that used the same tox file as other objects in ec13fefdacbaa3121ada4b6667f13d9517fefff4

**Comment by jetXS** [comment]
Time it takes to do the license check should be investigated

**Comment by jetXS** [comment]
Even with the latest update/improvements with TE Config, it does still take a really long time for that license error to come back and be shown to the user. Should be investigated when possible...

**Comment by bangnoise** [comment]
This is not yet fixed, awaiting a new SDK build from me (which is awaiting another issue).

**Comment by jetXS** [comment]
All good, no emergency. Thanks

**Comment by ddthejj** [comment]
Updated in 296ee86a6f5c5095867c5462deb5511712f7ab20
